name: Semantic Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - action.yaml
jobs:
  semantic-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: swarm-io/action-release-action@v1
        with:
          token: ${{ secrets.GIT_RUNNER_TOKEN }}